apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: {{ .Release.Namespace }}
  labels:
    app: hello
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: hello
---